server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    active: dev #配置环境
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_system?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.cc.entity
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    logic-delete-value: 1
    logic-not-delete-value: 0
book:
  book-name: ${random.int}_aaaa # 动态赋值
  #id: 1
  book-code: ${random.uuid}_code

